name: 02 CI Workflow

on:
  push:
    paths:
      - "app/**"
      - "tests/**"
      - ".github/workflows/02-ci.yml"
      - "**/*"
  schedule:
    - cron: '25 10 * * *'
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: List files
        run: ls -R

  scheduled-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Say Hello
        run: echo "Hello! This is the scheduled run."

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Run tests
        run: python -m unittest discover -s tests -v