name: Build Docker with ARG

on:
  workflow_dispatch:
    inputs:
      form-value:
        description: "Value for the form"
        required: true
        default: "default-value"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Build Docker image with ARG
        run: |
          echo "Building Docker image with FORM_VALUE=${{ github.event.inputs.form-value }}"
          docker build \
            --build-arg FORM_VALUE="${{ github.event.inputs.form-value }}" \
            -t tiny-health-app:${{ github.event.inputs.form-value }} .
          
      - name: Save Docker image as artifact
        run: docker save tiny-health-app:${{ github.event.inputs.form-value }} -o tiny-health-app.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tiny-health-app-image
          path: tiny-health-app.tar